# Reserva de memoria - Ejemplo en el conjunto de Cantor 

## Conjunto de Cantor {.scrollable}

El conjunto de Cantor se obtiene iterativamente partiendo del intervalo $(0,1)$ y, en cada iteración, dividiendo pasando del intervalo $(a,b)$ a $(a,\frac{a+b}{3}) \cup (2 \frac{a+b}{3} , b)$.

Si representamos el segmento $(a,b)$ por la tupla `(a,b)`, una iteración del cojunto de Cantor es un vector de tuplas. Una implementación posible es

```{julia}
function CantorIter(cantor)
    N = length(cantor)
    new_cantor = Array{Tuple{Float64,Float64}}(undef, 2 * N)

    for i = 1:N
        (a₁, a₂) = cantor[i]
        b₁ = (2 * a₁ + a₂) / 3
        b₂ = (a₁ + 2 * a₂) / 3

        new_cantor[2*i-1] = (a₁, b₁)
        new_cantor[2*i] = (b₂, a₂)
    end
    return new_cantor
end;
```

## Representando el conjunto de datos {.scrollable}

```{julia}
using Plots
function plotCantor(cantor::Array, n::Integer)
    p = plot(
        title="Conjunto de Cantor n = $n",
        xticks=([0, 1]), yticks=[],
        ylim=(-1, 1))
    for j = 1:length(cantor)
        p = plot!(
            [first(cantor[j]), last(cantor[j])],
            [0, 0],
            linewidth=2,
            axis=([], false),
            color=:black,
            label="")
    end
    return p
end;
```

Para representar $n$ pasos, aplicamos la fórmula iterativa

```{julia}
cantor = [(0, 1)]
@gif for n = 0:5
    plotCantor(cantor, n)
    global cantor = CantorIter(cantor)
end fps = 1
```

## Implementación recursiva {.scrollable}

La siguiente implementación recursiva devuelve directamente el paso $n$-ésimo
```{julia}
function CantorRec(a₁::Real, a₂::Real, n::Integer)
    if n > 0
        b₁ = (2 * a₁ + a₂) / 3
        b₂ = (a₁ + 2 * a₂) / 3
        return [CantorRec(a₁, b₁, n - 1); CantorRec(b₂, a₂, n - 1)]
    else
        return [(a₁, a₂)]
    end
end;
```

Comprobamos el timpo de computación

```{julia}
N = 25
@show N
println("Recursivo")
@time CantorRec(0.0, 1.0, N)
@time cantorRec = CantorRec(0.0, 1.0, N)
println("---")
println("Iterativo")
for i = 1:2
    @time begin
        global cantorIter = [(0, 1)]
        for n = 1:N
            cantorIter = CantorIter(cantorIter)
        end
    end
end

@show isequal(cantorRec, cantorIter);
```

## Utilizando `@view` {.scrollable}

En `julia` los vectores se pasan a la funciones por *sharing*, lo que ahorra memoria. 

Sin embargo, si pasamos un rango de un vector (por ejemplo `v[2:3]`) entonces se pasa una copia. Para que se pasa por *sharing*, y poder cambiarlo, se puede utilizar el macro `@view`.

```{julia}
function CantorRecAllocated!(a₁::Real, a₂::Real, cantor)
    if length(cantor) == 1
        cantor[1] = (a₁, a₂)
    else
        L = div(length(cantor), 2)
        b₁ = (2 * a₁ + a₂) / 3
        b₂ = (a₁ + 2 * a₂) / 3
        CantorRecAllocated!(a₁, b₁, @view cantor[1:L])
        CantorRecAllocated!(b₂, a₂, @view cantor[L+1:end])
    end
end;
```

## Eficiencia computacional {.scrollable}

```{julia}
println("Recursivo con reserva de memoria prueba 1")
print("Reserva de memoria = ")
@time cantorRecAllocated = Vector{Tuple{Float64,Float64}}(undef, 2^N)
print("Cálculo de los valores = ")
@time CantorRecAllocated!(0.0, 1.0, cantorRecAllocated)
println("----")
println("Recursivo con reserva de memoria prueba 2")
print("Reserva de memoria = ")
@time cantorRecAllocated2 = Vector{Tuple{Float64,Float64}}(undef, 2^N)
print("Cálculo de los valores = ")
@time CantorRecAllocated!(0.0, 1.0, cantorRecAllocated2)

@show isequal(cantorRecAllocated, cantorIter);
```

