# Diferenciación automática

## Números duales

Al hacer un desarrollo de Taylor
$$f(x+\delta) = f(x) + f'(x) \delta + \delta^2 \left( \frac{f''(x)}{2} + ... \right)$$
Para entender la derivada querríamos poder "tirar" los términos superiores

Sea $\varepsilon$ un elemento formal no-nulo tal que $\varepsilon^2=0$.

Podemos construir los números duales $a + b \varepsilon$ con $a,b \in \mathbb R$ y $\varepsilon \notin \mathbb R$.

Ejemplo tomado de [Video de Youtube del Prof Alan Edelman (MIT)](https://www.youtube.com/watch?v=vAp6nUMrKYg)

## Estructuras en Julia

Creamos una estructura de pares $(a,b)$ y la nombramos Dual 

```{julia}
struct Dual <: Number
    f::Tuple{Float64,Float64}
end
```

El constructor se genera de manera automática

. . .

```{julia}
Dual((1.0, 2.1))
``` 

---

Extendemos las funciones suma y resta a este tipo de elementos

```{julia}
import Base: +, -
+(x::Dual, y::Dual) = Dual(x.f .+ y.f);
-(x::Dual, y::Dual) = Dual(x.f .- y.f);
```

. . .

Y lo probamos
```{julia}
a = Dual((1.0, 2.0))
a + a
```

. . .

Nótese que si $f(x) = a + bx, g(x) = c + dx$ entonces $\frac{d}{dx}\Big|_{x=0} (f+g) = b + d$.

--- {.scrollable}

Bajo la premisa $\varepsilon^2 = 0$, para multiplicar:
$$
    (a+b\varepsilon)(c+d\varepsilon) = ac + (bc + ad)\varepsilon + bd \varepsilon^2 = ac + (bc + ad)\varepsilon.
$$

. . .

Nótese si $f(x) = a + bx, g(x) = c + dx$ entonces 
$$
    \frac{d}{dx}\Big|_{x=0} f{g}  = bc + ad.
$$

---

Para dividir hay un truco sencillo
$$
    \frac{a+b\varepsilon}{c+d\varepsilon} 
    = \frac{(a+b\varepsilon)(c-d\varepsilon)}{(c+d\varepsilon)(c-d\varepsilon)} = \frac{(a+b\varepsilon)(c-d\varepsilon)}{c^2-d^2 \varepsilon^2}
    = \frac{(a+b\varepsilon)(c-d\varepsilon)}{c^2}
$$

. . .

Finalmente
$$
    \frac{a+b\varepsilon}{c+d\varepsilon} = \frac{a}{c} + \frac{bc - ad}{c^2} \varepsilon
$$

. . .

Nótese si $f(x) = a + bx, g(x) = c + dx$ entonces 
$$
    \frac{d}{dx}\Big|_{x=0} \frac{f}{g}  = \frac{bc - ad}{c^2}\dots. 
$$

. . .

```{julia}
import Base: *, /
*(x::Dual, y::Dual) = Dual((x.f[1] * y.f[1], x.f[1] * y.f[2] + x.f[2] * y.f[1]))
/(x::Dual, y::Dual) = Dual((
    x.f[1] / y.f[1],
    (x.f[2] * y.f[1] - x.f[1] * y.f[2]) / (y.f[1]^2)
));
```

--- 

**Teorema.** Si $f= p(x) / q(x)$ con $p, q\in \mathbb R[X]$ entonces 
$$
    f(x + \varepsilon) = f(x) + f'(x) \varepsilon.
$$

Definimos una variable llamada $\varepsilon$

```{julia}
ϵ = Dual((0, 1))
```

así definimos

```{julia}
#| scrolled: true
diff(g, x) = (g(x + ϵ)).f[2];
```


## Un poco de maquillaje

Para verlo bonito

```{julia}
Base.show(io::IO, x::Dual) = print(io, x.f[1], " + ", x.f[2], " ε")
```

. . .

```{julia}
a
```

---

Añadimos una función de convertir, por defecto

```{julia}
#| scrolled: true
import Base: convert
convert(::Type{Dual}, x::Real) = Dual((x, zero(x)));
```

. . .

Por último, tenemos que explicar a Julia que si intenta sumar un real y un dual, hay que "promocionar" el real a dual

```{julia}
import Base: promote_rule
promote_rule(::Type{Dual}, ::Type{<:Number}) = Dual;
```

Vemos que esto ya nos permite interoperar con `Float` y `Dual`

```{julia}
#| scrolled: true
1.0 / (1.0 + ϵ)
```

## Ejemplo de cálculo de derivadas

Utilizando estos números duales, muchas funciones se pueden derivar de esta forma.

Por ejemplo, tomemos la raíz cuadrada con la formula babilonia 

```{julia}
function sqrtBab(x; N=10)
    t = (1 + x) / 2
    for i = 2:N
        t = (t + x / t) / 2
    end
    return t
end

sqrtBab(1.35) - sqrt(1.35)
```

. . .

Y si aplicamos números duales tenemos que coincide con la derivada simbólica

```{julia}
#| scrolled: true
dsqrt(x) = 0.5 / √x
dsqrt(1.35) - diff(sqrtBab, 1.35)
```

. . .

Mediante diferencias finitas
```{julia}
difffin(; x, h) = (sqrt(x + h) - sqrt(x)) / h
dsqrt(1.35) - difffin(x=1.35, h=sqrt(eps()))
```

```{julia}
h = eps()
dsqrt(1.35) - difffin(x=1.35, h=eps())
```

## Pinceladas de Álgebra

Recordamos el conjunto de números complejos $\mathbb C$ es 

$a + b i$ donde $i \notin \mathbb R$

y coincide con 

$$
    \mathbb R[x] / \langle x^2 + 1 \rangle 
$$

. . .

Del mismo modo, $a + b \varepsilon$ donde $\varepsilon \notin \mathbb R$ y $\varepsilon^2 = 0$ es lo mismo que

. . .

$$
    \mathbb R[x] / \langle x^2 \rangle 
$$